name: Herald_flutter
description: Herald is a simple application that can download and show trains schedule of Belarus (schedule provided by https://rasp.rw.by).

publish_to: 'none'

version: 0.1.0-dev2

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lint: ^1.3.0
  auto_route: ^0.6.9
  http: ^0.12.2
  html: ^0.14.0+4
  intl: ^0.16.1
  flutter_svg: ^0.19.1
  built_value: ^7.1.0
  built_collection: ^4.3.2
  sealed_class: ^3.0.0
  built_redux: ^7.5.11
  flutter_built_redux: ^0.6.0
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.9
  built_value_generator: ^7.1.0
  sealed_class_generator: ^3.0.0
  hive_generator: ^0.8.2
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/

include: package:lint/analysis_options.yaml